title: The Blog of Juho
description: This is my blog. Nothing more.
authors: Juho Tykkälä
theme: jekyll-theme-slate
twitter: tykkala

paginate: 5
url: "blog.enyone.rainio.org"
permalink: /:title
excerpt_separator: end of TL;DR so now go and read...

gems:
  - jekyll-sitemap
