title: The Blog of Juho
description: This is my blog. Nothing more.
authors: Juho Tykkälä
theme: jekyll-theme-hacker
twitter: tykkala

paginate: 5
url: "blog.rainio.org"
permalink: /:title
excerpt_separator: <!--more-->

gems:
  - jekyll-sitemap
